/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edd.py2_201520498.Win;

import edd.py2_201520498.EDDPY2_201520498;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileSystemView;

/**
 *
 * @author herre
 */
public class MainWin extends javax.swing.JFrame {

    Login_User Login = new Login_User();
    EDDPY2_201520498 Server = new EDDPY2_201520498();
    String Usuario = Login.Nombre;
    String NombreC;
    public static String NombreDelaCarpetaDeCargadelArbol;

    /**
     * Creates new form MainWin
     */
    public MainWin() {
        initComponents();
        NameUser.setText(Usuario);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CreateFolders = new javax.swing.JButton();
        ModifyFolders = new javax.swing.JButton();
        DeleteFolders = new javax.swing.JButton();
        ShareFolders = new javax.swing.JButton();
        CreateFolders1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        CreateArchive = new javax.swing.JButton();
        ModifyArchive = new javax.swing.JButton();
        DeleteArchive = new javax.swing.JButton();
        ShareArchive = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        NameUser = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Folders"));

        CreateFolders.setText("Create");
        CreateFolders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateFoldersActionPerformed(evt);
            }
        });

        ModifyFolders.setText("Modify");
        ModifyFolders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifyFoldersActionPerformed(evt);
            }
        });

        DeleteFolders.setText("Delete");
        DeleteFolders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteFoldersActionPerformed(evt);
            }
        });

        ShareFolders.setText("Share");
        ShareFolders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShareFoldersActionPerformed(evt);
            }
        });

        CreateFolders1.setText("Create in Other ");
        CreateFolders1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateFolders1ActionPerformed(evt);
            }
        });

        jButton4.setText("Delete in Other");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CreateFolders1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ModifyFolders, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DeleteFolders, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ShareFolders, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CreateFolders, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CreateFolders)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CreateFolders1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ModifyFolders)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DeleteFolders)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ShareFolders)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Archive"));

        CreateArchive.setText("Create");
        CreateArchive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateArchiveActionPerformed(evt);
            }
        });

        ModifyArchive.setText("Modify Content");
        ModifyArchive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifyArchiveActionPerformed(evt);
            }
        });

        DeleteArchive.setText("Delete");

        ShareArchive.setText("Share");
        ShareArchive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShareArchiveActionPerformed(evt);
            }
        });

        jButton3.setText("Bulk");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setText("Downland");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CreateArchive, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ModifyArchive, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(DeleteArchive, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ShareArchive, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(CreateArchive)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ModifyArchive)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DeleteArchive)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ShareArchive)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setText("USAC FILE DRIVE");

        NameUser.setEditable(false);
        NameUser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButton1.setText("Reports");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NameUser, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NameUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CreateFoldersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateFoldersActionPerformed
        // TODO add your handling code here:
        NombreC = JOptionPane.showInputDialog("Ingresar Nombre Carpeta");
        CrearCarpeta();
    }//GEN-LAST:event_CreateFoldersActionPerformed

    private void CreateFolders1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateFolders1ActionPerformed
        // TODO add your handling code here:
        CrearEnOtra();
        //Server.ImprimirTodasLasCarpetas(Usuario);
    }//GEN-LAST:event_CreateFolders1ActionPerformed

    private void ModifyFoldersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyFoldersActionPerformed
        // TODO add your handling code here:
        ModificarNombreCarpeta();
    }//GEN-LAST:event_ModifyFoldersActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Server.ImprimirTodasLasCarpetas(Usuario);
        AgraficarAVL();
        Server.InsertardesdeHash(Usuario, "Generando Imagenes");
        VentanaPrincipal a = new VentanaPrincipal();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        Login.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void CreateArchiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateArchiveActionPerformed
        // TODO add your handling code here:
        AgreagarNuevosArchivos();
    }//GEN-LAST:event_CreateArchiveActionPerformed

    private void ModifyArchiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyArchiveActionPerformed
        // TODO add your handling code here:
        ModificarContenido();
    }//GEN-LAST:event_ModifyArchiveActionPerformed

    private void ShareFoldersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShareFoldersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ShareFoldersActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        TodoCargar();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void DeleteFoldersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteFoldersActionPerformed
        // TODO add your handling code here:
        EliminarCarpetasPadre();
    }//GEN-LAST:event_DeleteFoldersActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        EliminarCarpetasHijas();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        DescargarArchivo();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void ShareArchiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShareArchiveActionPerformed
        // TODO add your handling code here:
        CompartirArchivo();
    }//GEN-LAST:event_ShareArchiveActionPerformed

    public void CompartirArchivo() {
        String NombreUsuario = JOptionPane.showInputDialog("Nombre Usuario");
        String NombreCarpeta = JOptionPane.showInputDialog("Nombre del Archivo");
        if (Server.Compartir(NombreUsuario) && Server.VerificarSiExisteArchivo(Usuario,NombreCarpeta)) {
            String Contendio = Server.TraerContenido(Usuario, NombreCarpeta);
            System.out.println(Contendio);
            Server.AgregarArchivosACarpetas(NombreUsuario,"/",NombreCarpeta,Contendio);
        }else{
            System.out.println("No se puedo Compartir");
        }

    }

    public void AgraficarAVL() {
        String NombreCarpeta = JOptionPane.showInputDialog("Nombre de la Carpeta");
        Server.ImprimirAVL(Usuario, NombreCarpeta);

    }

    public void DescargarArchivo() {
        String NombreArchivo = JOptionPane.showInputDialog("Nombre del Archivo");
        String NombreCarpeta = JOptionPane.showInputDialog("Nombre de la Carpeta");
        if (Server.DescargarArchivo(Usuario, NombreCarpeta, NombreArchivo)) {
            System.out.println("Si se Descarga el archovp");
        } else {
            System.out.println("No se ha podido descargar el arhcivo ");
        }

    }

    public void EliminarCarpetasPadre() {
        String NombreHija = JOptionPane.showInputDialog("Nombre de la Carpeta");
        if (Server.EliminarCarpetarPadre(Usuario, NombreHija)) {
            Server.InsertardesdeHash(Usuario, "Se Elimino la Carpeta" + NombreHija);
        } else {
            Server.InsertardesdeHash(Usuario, "No se pudo Eliminar la Carpeta " + NombreHija);
        }
    }

    public void EliminarCarpetasHijas() {
        String NombreHija = JOptionPane.showInputDialog("Nombre de la Carpeta");
        String NombrePadre = JOptionPane.showInputDialog("Nombre de la Carpeta donde se Encuentra");
        if (Server.EliiminarCarpetasHijas(Usuario, NombrePadre, NombreHija)) {
            Server.InsertardesdeHash(Usuario, "Se Elimino la Carpeta" + NombreHija);
        } else {
            Server.InsertardesdeHash(Usuario, "No se pudo Eliminar la Carpeta " + NombreHija);
        }

    }

    public void TodoCargar() {
        NombreDelaCarpetaDeCargadelArbol = JOptionPane.showInputDialog("Nombre de la Carpeta a Crear los Archivos");
        try {
            Bulk();

        } catch (IOException ex) {
            Logger.getLogger(MainWin.class.getName()).log(Level.SEVERE, null, ex);
        }
        Server.ImprimirAVL(Usuario, NombreDelaCarpetaDeCargadelArbol);
    }

    public void Bulk() throws IOException {
        JFileChooser jfc = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
        int returnValue = jfc.showOpenDialog(null);
        String a = "";
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File selectedFile = jfc.getSelectedFile();
            System.out.println(selectedFile.getAbsolutePath());
            a = selectedFile.getAbsolutePath();
            Read(a);

        }

    }

    public void Read(String ruta) throws FileNotFoundException, IOException {
        File file = new File(ruta);
        BufferedReader br = new BufferedReader(new FileReader(file));
        String st;
        String a = "";
        Scanner sc = new Scanner(file);
        while ((st = br.readLine()) != null) {
            a += st + "\n";
        }
        System.out.println(a);
        CompletarRead(a);
    }

    public void CompletarRead(String archivo) {
        String[] fila = archivo.split("\n");
        String[] Pi;
        String NombreArchivo, Contendio;
        for (int i = 0; i < fila.length; i++) {
            //Pi = fila[i].split(";");
            Pi = fila[i].split(",");
            NombreArchivo = Pi[0];
            Contendio = Pi[1].replace("\"", "");
            if (!NombreArchivo.equalsIgnoreCase("Archivo") && !Contendio.equalsIgnoreCase("Contenido")) {
                if (Server.AgregarArchivosACarpetas(Usuario, NombreDelaCarpetaDeCargadelArbol, NombreArchivo, Contendio)) {
                    System.out.println("Si se Agregan ");
                } else {
                    System.out.println("No Se agregan ");
                }
                // System.out.println("Usuario:" +Usuario +" Password:"+Pass+" Pass Encriptado:"+Encriptacion(Pass));
            }
        }
    }

    public String Time() {
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy HH:mm:ss");
        String a = dateFormat.format(new Date());
        return a;
    }

    public void ModificarContenido() {
        String NombreArchivo = JOptionPane.showInputDialog("Nombre del Archivo");
        String Contenido = JOptionPane.showInputDialog("Nuevo Contenido");
        String Carpeta = JOptionPane.showInputDialog("Nombre de Carpeta del Archivo");
        if (Server.ModificarContenidoArchivos(Usuario, Carpeta, NombreArchivo, Contenido)) {
            JOptionPane.showMessageDialog(null, "Se Modifico el Archivo" + NombreArchivo + " a la Carpeta: " + Carpeta);
            System.out.println("Se Modifico el Archivo " + NombreArchivo + " a la Carpeta: " + Carpeta);
        } else {
            System.out.println("No se pudo agregar el Archivo");
        }
        Server.ImprimirAVL(Usuario, Carpeta);
    }

    public void AgreagarNuevosArchivos() {
        String NombreArchivo = JOptionPane.showInputDialog("Nombre del Archivo");
        String Contenido = JOptionPane.showInputDialog("Contenido");
        String Carpeta = JOptionPane.showInputDialog("Carpeta de Creacion del Archivo");
        if (Server.AgregarArchivosACarpetas(Usuario, Carpeta, NombreArchivo, Contenido)) {
            JOptionPane.showMessageDialog(null, "Se Agrego el Archivo" + NombreArchivo + " a la Carpeta: " + Carpeta);
            System.out.println("Se Agrego el Archivo" + NombreArchivo + " a la Carpeta: " + Carpeta);
        } else {
            System.out.println("No se pudo agregar el Archivo");
        }
        //   Server.ImprimirAVL(Usuario, Carpeta);
    }

    public void ModificarNombreCarpeta() {
        String NombreNuevo = JOptionPane.showInputDialog("Ingresar El Nuevo Nombre de la Carpeta");
        String NombreViejo = JOptionPane.showInputDialog("Ingresar el Nombre Viejo de la Carpeta");

        if (Server.ModificarNombreCarpetas(Usuario, NombreViejo, NombreNuevo)) {

        } else {
            JOptionPane.showMessageDialog(null, "Ya hay Carpetas con ese Nombre");
            System.out.println("Ocurrio un problema al insertar");
        }

    }

    public void CrearEnOtra() {
        String NombreNueva = JOptionPane.showInputDialog("Ingresar Nombre Carpeta Nueva");
        String NombrePadre = JOptionPane.showInputDialog("Ingresar Nombre En donde la quiere Crear");
        if (Server.AgrearEnOtra(Usuario, NombrePadre, NombreNueva)) {
            // Server.ImprimirTodasLasCarpetas(Usuario);
        } else {
            System.out.println("Ocurrio un problema al insertar");
        }
    }

    public void CrearCarpeta() {
        if (Server.AgregarCarpetaNueva(Usuario, NombreC)) {

            System.out.println("Si se Ingreso la Carpeta");
        } else {
            System.out.println("No se ingreso la carpeta");
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWin().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateArchive;
    private javax.swing.JButton CreateFolders;
    private javax.swing.JButton CreateFolders1;
    private javax.swing.JButton DeleteArchive;
    private javax.swing.JButton DeleteFolders;
    private javax.swing.JButton ModifyArchive;
    private javax.swing.JButton ModifyFolders;
    private javax.swing.JTextField NameUser;
    private javax.swing.JButton ShareArchive;
    private javax.swing.JButton ShareFolders;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
